services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: icestream-kafka

    ports:
      - "9092:9094"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

    volumes:
      - kafka_data:/var/lib/kafka/data

  jobmanager:
    image: flink:1.18.1-scala_2.12
    container_name: icestream-jobmanager

    ports:
      - "8081:8081"

    command: jobmanager

    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        jobmanager.bind-host: 0.0.0.0
        rest.address: 0.0.0.0

    volumes:
      - ./flink/lib/iceberg-flink-runtime-1.18-1.5.0.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.5.0.jar
      - ./flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar:/opt/flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar
      - ./flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./flink/lib:/opt/flink/usrlib
      - ./warehouse:/opt/flink/warehouse

  taskmanager:
    image: flink:1.18.1-scala_2.12
    container_name: icestream-taskmanager

    depends_on:
      - jobmanager

    command: taskmanager

    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.host: taskmanager
        taskmanager.bind-host: 0.0.0.0
        taskmanager.rpc.port: 6122
        taskmanager.numberOfTaskSlots: 2

    volumes:
      - ./flink/lib/iceberg-flink-runtime-1.18-1.5.0.jar:/opt/flink/lib/iceberg-flink-runtime-1.18-1.5.0.jar
      - ./flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar:/opt/flink/lib/flink-sql-connector-kafka-3.1.0-1.18.jar
      - ./flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./flink/lib:/opt/flink/usrlib
      - ./warehouse:/opt/flink/warehouse

volumes:
  kafka_data: